name: CI Check

on:
  pull_request:
    branches:
      - dev

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test